version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - dependencies
    rebase-strategy: disabled
